CDShopWeb/Areas/Admin/Controllers/CompanyController.cs
using CDShop.DataAccess.Repository.IRepository;
using CDShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace CDShopWeb.Areas.Admin.Controllers;
[Area(nameof(Admin))]

public class CompanyController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

     public CompanyController(IUnitOfWork unitOfWork)
     {
        _unitOfWork = unitOfWork;
     }

     public IActionResult Index()
     {
        return View();
     }

     public IActionResult Upsert(int? id)
     {
        Company company = new();

        if( id == 0 || id == null)
        {
            return View(company);
        }
        else
        {
            company = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == id);
            return View(company);
        }
     }

     [HttpPost]
     [ValidateAntiForgeryToken]

     public IActionResult Upsert(Company company)
     {
        if(ModelState.IsValid)
        {
            if(company.Id== 0)
            {
                _unitOfWork.Company.Add(company);
            }
            else
            {
                _unitOfWork.Company.Update(company);
            }
             _unitOfWork.Save();
        }
         return RedirectToAction(nameof(Index));
     }

    #region API CALLS

    public IActionResult GetAll()
    {
        var companyList = _unitOfWork.Company.GetAll();
        return Json(new { data = companyList });
    }
    [HttpDelete]

    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == id);
        if (id == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }
        _unitOfWork.Company.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Deleted" });
    }

    #endregion

}

CDShopWeb/Areas/Admin/Controllers/GenreController.cs
using CDShop.DataAccess.Repository.IRepository;
using CDShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CDShopWeb.Areas.Admin.Controllers;
[Area("Admin")]

    public class GenreController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public GenreController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Genre> objGenreList = _unitOfWork.Genre.GetAll();
            return View(objGenreList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Genre obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Genre.Add(obj);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            var genreFromDb = _unitOfWork.Genre.GetFirstOrDefault(u => u.Id == id);

            if (genreFromDb == null)
            {
                return NotFound();
            }
            return View(genreFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Edit(Genre obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Genre.Update(obj);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var genreFromDb = _unitOfWork.Genre.GetFirstOrDefault(u => u.Id == id);
            if (genreFromDb == null)
            {
                return NotFound();
            }
            return View(genreFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeletePost(int? id)
        {
            var genreFromDb = _unitOfWork.Genre.GetFirstOrDefault(u => u.Id == id);
            if (genreFromDb == null)
            {
                return NotFound();
            }
            _unitOfWork.Genre.Remove(genreFromDb);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }

CDShopWeb/Areas/Admin/Controllers/PackageController.cs
using CDShop.DataAccess.Repository.IRepository;
using CDShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CDShopWeb.Areas.Admin.Controllers;
[Area("Admin")]
    public class PackageController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PackageController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Package> objPackageList = _unitOfWork.Package.GetAll();
            return View(objPackageList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Package obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Package.Add(obj);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            var packageFromDb = _unitOfWork.Package.GetFirstOrDefault(u => u.Id == id);

            if (packageFromDb == null)
            {
                return NotFound();
            }
            return View(packageFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Edit(Package obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Package.Update(obj);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var packageFromDb = _unitOfWork.Package.GetFirstOrDefault(u => u.Id == id);
            if (packageFromDb == null)
            {
                return NotFound();
            }
            return View(packageFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeletePost(int? id)
        {
            var packageFromDb = _unitOfWork.Package.GetFirstOrDefault(u => u.Id == id);
            if (packageFromDb == null)
            {
                return NotFound();
            }
            _unitOfWork.Package.Remove(packageFromDb);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }

CDShopWeb/Areas/Admin/Controllers/ProductController.cs
using CDShop.DataAccess.Repository.IRepository;
using CDShop.Models;
using CDShop.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using System.Collections.Generic;

namespace CDShopWeb.Areas.Admin.Controllers;
[Area("Admin")]

public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public ProductController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Upsert(int? id)
    {
        ProductVM productVM = new()
        {
            Product = new(),
            GenreList = _unitOfWork.Genre.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }),
            PackageList = _unitOfWork.Package.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }),
        };
        if (id == 0 || id == null)
        {
            return View(productVM);
        }
        else
        {
            productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            return View(productVM);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]

    public IActionResult Upsert(ProductVM obj)
    {
        if (ModelState.IsValid)
        {
            if (obj.Product.Id == 0)
            {
                _unitOfWork.Product.Add(obj.Product);
            }
            else
            {
                _unitOfWork.Product.Update(obj.Product);
            }
        }
        _unitOfWork.Save();
        return RedirectToAction(nameof(Index));
    }



    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var productList = _unitOfWork.Product.GetAll(includeProperties: "Genre,Package");
        return Json(new { data = productList });
    }
    [HttpDelete]
    public IActionResult Delete(int? id)
    {

        var obj = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == id);
        if (id == null)
            return Json(new { success = false, message = "Error while deleting" });

        _unitOfWork.Product.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Deleted" });
    }

    #endregion
}
    

CDShopWeb/Views/Shared/_Layout.cshtml
@using CDShop.Utility
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CD Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CDShopWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CD Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">  
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee) )
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Genre" asp-action="Index">Genre</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Package" asp-action="Index">Package</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                </div>
                            </li>
                        }                      
                        <li class="nav-item">
                            <a class=nav-link asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart4"></i>
                            </a>
                        </li>                      
                        <li class="nav-item">
                            <a class=nav-link asp-area="Admin" asp-controller="Order" asp-action="Index">
                               Manage Order
                            </a>
                       </li>                                   
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container flex-grow-1">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>